name: Issue Tracker API
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install packages
        run: npm run install-server
      - name: Run tests
        run: npm test --prefix server